# Config for downloading files only.

csb: # adjust year in Snakefile.
  base_html: "https://www.nass.usda.gov/Research_and_Science/Crop-Sequence-Boundaries/datasets"
  raw_dir: "data/CSB"
  output_dir: "data/CSB"

cdl:
  base_html: "https://www.nass.usda.gov/Research_and_Science/Cropland/Release/datasets"
  year: [2014, 2025] #2014-2024
  raw_dir: "data/CDL"
  output_dir: "data/CDL"

elevation:
  base_html: "https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/1/TIFF/current"
  y_range: [38, 50] #N38 to N49
  x_range: [81, 92] #W081 to W091
  raw_dir: "data/Geo/elevation/tiles"
  output_dir: "data/Geo/elevation"

census_tract: # define census tract file in Snakefile
  base_html: "https://www2.census.gov/geo/tiger/GENZ2023/shp"
  raw_dir: "data/Census/census_tract"
  output_dir: "data/Census/census_tract"

state_bound: # define state boundary file in Snakefile
  base_html: "https://www2.census.gov/geo/tiger/GENZ2023/shp"
  raw_dir: "data/Census/state_bound"
  output_dir: "data/Census/state_bound"

roads: 
  base_html: "https://www2.census.gov/geo/tiger/TIGER2023/PRISECROADS"
  prefixes: ["18", "26", "39", "17", "21", "42", "54", "55"] # main states & surrounding states
  raw_dir: "data/Census/road/raw"
  output_dir: "data/Census/road"

watershed:
  base_html: "https://prd-tnm.s3.amazonaws.com/StagedProducts/Hydrography/NHD/State/Shape"
  states: ["Ohio", "Indiana", "Michigan"]
  raw_dir: "data/Geo/watershed/raw"
  output_dir: "data/Geo/watershed"